[toolchain]
channel = "nightly"
targets = [ 
    "armv7-linux-androideabi", 
    "i686-linux-android", 
    "aarch64-linux-android", 
    "x86_64-linux-android", 
    "aarch64-apple-ios", 
    "aarch64-apple-ios-sim", 
    "x86_64-apple-ios"
]
